### ISSUE TITLE
Webspeech API dumps text to browser screen

### ISSUE THREAD

**Issue by squareping** [SahilAggarwal2004/react-text-to-speech#1]
Hi,

I have been experimenting with WebSpeech API. For some reasons, the text as a result of SpeechRecognition or TextToSpeech component are output on browser screen.

I thought this is a verbose mode for debugging or something, but I cant override it.

I wonder why other users have not reported it. Maybe, I did not have it install correctly or something.

Please advise.

Thanks
Peter Pham

**Comment by SahilAggarwal2004** [comment]
Hey @squareping, I am closing this issue since your issue has been resolved.
