### ISSUE TITLE
Speech Text Change from code behind

### ISSUE THREAD

**Issue by hxgst2** [SahilAggarwal2004/react-text-to-speech#3]
Hi Team,

How to do you change text property from code behind since i want to change text at run time. Appreciate your help.

**Comment by SahilAggarwal2004** [comment]
> Hi Team,
> 
> How to do you change text property from code behind since i want to change text at run time. Appreciate your help.

Hi @hxgst2, thanks for reaching out.
Can you please show me the exact use case of what you want, as the information you provided is not clear enough.

**Comment by SahilAggarwal2004** [comment]
From what I can understand from your issue, I would suggest you to use the `useState` hook in react to store the `text` state and change it using `setText` and then pass the `text` state in `text` property.
I would also suggest you to upgrade to the latest version `v0.12.1` first and I have handled text changes in the latest version.

**Comment by SahilAggarwal2004** [comment]
Hi @hxgst2, since there hasn't been any response from your side, I'm closing this issue for now.
Please feel free to reopen it if needed.
